image: alpine:latest

build-job:
  stage: build
  image: espressif/idf:release-v4.2
  script: |
    git pull
    git submodule update --init --recursive
    idf.py build
    cp build/epaper-idf.bin .
  artifacts:
    paths:
      - epaper-idf.bin

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
