image: alpine:latest

build-job:
  stage: build
  image: espressif/idf:release-v4.2
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git submodule update --init --recursive
    - mkdir certs && touch certs/ca_cert.pem
    - cp sdkconfig.ci sdkconfig
    - idf.py build
    - cp build/partition_table/partition-table.bin .
    - cp build/ota_data_initial.bin .
    - cp build/bootloader/bootloader.bin .
    - cp build/epaper-idf.bin .
  artifacts:
    name: "epaper-idf-bin-$CI_COMMIT_REF_NAME"
    paths:
      - partition-table.bin
      - ota_data_initial.bin
      - bootloader.bin
      - epaper-idf.bin
  only:
    - master
    - v0.1

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
